language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=1.5.8
  - DJANGO=1.6.5
install: pip install -q Django==$DJANGO six coveralls
script: python setup.py coverage
after_success: cd testproject && coveralls
